server:
  port: 8080

spring:
  ### datasource
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: admini
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 900000
      maximum-pool-size: 30
      minimum-idle: 10
      pool-name: HikariCP
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: admini
    timeout: 1000
    pool:
      max-active: 20
      max-idle: 10
      max-wait: -1
      min-idle: 0