# 配置freemarker
spring:
  freemarker:
    cache: false # 是否开启模板缓存，默认true。开发时可以设置为 false
    check-template-location: true # 是否检查模板路径是否存在，默认true
    template-loader-path: classpath:/templates # 设置ftl文件路径
    content-type: text/html # 设置文档类型
    charset: UTF-8 # 设置页面编码格式
    suffix: .ftl # 指定模板的后缀，默认为:.ftl
  mvc:
    static-path-pattern: /static/** # 设置静态文件路径，js,css等