spring:
  thymeleaf:
    cache: false # 是否开启模板缓存，默认true。开发时可以设置为 false
    check-template-location: true # 是否检查模板路径是否存在，默认true
    enabled: true # 是否允许MVC使用Thymeleaf，默认为: true
    encoding: UTF-8 # 指定模板的编码，默认为: UTF-8
    mode: LEGACYHTML5 # 指定模板的模式，具体查看StandardTemplateModeHandlers，默认为: HTML5，LEGACYHTML5关闭严格模式
    prefix: classpath:/templates/ # 指定模板的前缀，默认为:classpath:/templates/
    suffix: .html # 指定模板的后缀，默认为:.html
    servlet:
      content-type: text/html # 指定Content-Type，默认为: text/html
  mvc:
    static-path-pattern: /static/** # 指定静态资源处理路径
    view:
      suffix: .html


# 配置freemarker
spring:
  freemarker:
    cache: false # 是否开启模板缓存，默认true。开发时可以设置为 false
    check-template-location: true # 是否检查模板路径是否存在，默认true
    template-loader-path: classpath:/templates # 设置ftl文件路径
    content-type: text/html # 设置文档类型
    charset: UTF-8 # 设置页面编码格式
    suffix: .ftl # 指定模板的后缀，默认为:.ftl
  mvc:
    static-path-pattern: /static/** # 设置静态文件路径，js,css等